# Generated by Django 2.1.6 on 2019-03-05 20:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinputchatbot',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='userinputchatbot',
            name='text',
            field=models.TextField(max_length=70, null=True),
        ),
    ]
